### ISSUE TITLE
CodeBuild Failure 

### ISSUE THREAD

**Issue by Suba-delo** [awslabs/aws-deployment-framework#182] opened 2019-11-12 08:32 UTC
Hi @bundyfx ,

There is code build failure again with the error ;
```sh
"Command did not exit successfully cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null exit status 1 
[Container] 2019/11/12 08:22:09 Phase complete: BUILD State: FAILED 
[Container] 2019/11/12 08:22:09 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null. Reason: exit status 1 "
```

**A newer version of the CDK CLI (>= 1.16.0) is necessary to interact with this app 
 **

Does it mean that, ADF needs an update now ??

**Comment by ErikMeinders** [comment] 2019-11-12 12:35
Same issue here. AWS SAR mentions V2.1.1 but here on GH V2.1.0 seems to be the latest ... I have 2.1.0 running. Can't find documentation on 2.1.1. Just wondering is 2.1.1 fixes this issue. Anyone?

**Comment by Suba-delo** [comment] 2019-11-12 13:11
![image](https://user-images.githubusercontent.com/54883418/68674203-b5e0f780-0555-11ea-9076-bf5d64f4d7b5.png)

I tried updating the requirement.txt file with **jsii==0.20.3** , but then that ended up with other error as **cdk 1.13.1** is compatible with **jsii==0.19.0** 

I think Flynn(@bundyfx ) has locked the CDK to 1.13.1 version ,if im not wrong.. Pipeline will never work as long as this gets fixed. The better idea is to update CDK to 1.16.1 ??

**Comment by bundyfx** [comment] 2019-11-12 13:14
I am testing with 1.16.2 (and jsi 0.20.3) right now, will make release with this version if all works as intended..

**Comment by Suba-delo** [comment] 2019-11-12 13:14
> Same issue here. AWS SAR mentions V2.1.1 but here on GH V2.1.0 seems to be the latest ... I have 2.1.0 running. Can't find documentation on 2.1.1. Just wondering is 2.1.1 fixes this issue. Anyone?

Im already running 2.1.1 version .. it doesnt work for me either

**Comment by Suba-delo** [comment] 2019-11-12 13:16
> I am testing with 1.16.2 (and jsi 0.20.3) right now, will make release with this version if all works as intended..

Sounds good ! Looking forward to the new release soon

**Comment by bundyfx** [comment] 2019-11-12 14:25
v2.1.2 is now on SAR which resolves updates CDK version to 1.16.2 along with updating some deprecated functionality. Please let me know how it goes.

**Comment by ErikMeinders** [comment] 2019-11-12 15:00
Updated 2.1.0 to 2.1.2 just now. 

>  
[Container] 2019/11/12 14:52:22 Running command pip install -r adf-build/requirements.txt -q -t ./adf-build 
ERROR: aws-cdk-cx-api 1.16.2 has requirement jsii~=0.20.4, but you'll have jsii 0.19.0 which is incompatible. 
ERROR: aws-cdk-region-info 1.16.2 has requirement jsii~=0.20.4, but you'll have jsii 0.19.0 which is incompatible. 
WARNING: Target directory /codebuild/output/src701789163/src/adf-build/tests already exists. Specify --upgrade to force replacement. 
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available. 
You should consider upgrading via the 'pip install --upgrade pip' command. 
 
[Container] 2019/11/12 14:52:43 Phase complete: PRE_BUILD State: SUCCEEDED 
[Container] 2019/11/12 14:52:43 Phase context status code:  Message:  
[Container] 2019/11/12 14:52:43 Entering phase BUILD 
[Container] 2019/11/12 14:52:43 Running command cdk --version 
1.13.1 (build 96cfc63) 
 
[Container] 2019/11/12 14:52:44 Running command chmod 755 adf-build/cdk/execute_pipeline_stacks.py adf-build/cdk/generate_pipeline_inputs.py adf-build/cdk/generate_pipeline_stacks.py 
 
[Container] 2019/11/12 14:52:44 Running command python adf-build/cdk/generate_pipeline_inputs.py 
2019-11-12 14:52:44,743 | INFO | __main__ | ADF Version 2.1.2 | (generate_pipeline_inputs.py:169) 
2019-11-12 14:52:44,743 | INFO | __main__ | ADF Log Level is INFO | (generate_pipeline_inputs.py:170) 
2019-11-12 14:52:44,758 | INFO | deployment_map | Loading deployment_map file deployment_map.yml | (deployment_map.py:61) 
2019-11-12 14:52:45,785 | INFO | rule | Ensuring Stack State for Event Rule forwarding from 284645684760 to 245359594842 | (rule.py:54) 
2019-11-12 14:52:46,118 | INFO | repo | Ensuring State for Codecommit Repository Stack sample-iam on Account 245359594842 | (repo.py:79) 
 
[Container] 2019/11/12 14:53:10 Running command cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null 
2019-11-12 14:53:12,757 | INFO | __main__ | ADF Version 2.1.2 | (generate_pipeline_stacks.py:25) 
2019-11-12 14:53:12,757 | INFO | __main__ | ADF Log Level is INFO | (generate_pipeline_stacks.py:26) 
2019-11-12 14:53:12,763 | INFO | cdk_stacks.main | Pipeline creation/update of audit-cis-cloudtrail commenced | (main.py:31) 
2019-11-12 14:53:12,908 | INFO | cdk_stacks.main | Pipeline creation/update of audit-vpc-flowlogs commenced | (main.py:31) 
2019-11-12 14:53:12,981 | INFO | cdk_stacks.main | Pipeline creation/update of audit-cis commenced | (main.py:31) 
2019-11-12 14:53:13,041 | INFO | cdk_stacks.main | Pipeline creation/update of audit-cis-config commenced | (main.py:31) 
2019-11-12 14:53:13,122 | INFO | cdk_stacks.main | Pipeline creation/update of sample-iam commenced | (main.py:31) 
2019-11-12 14:53:13,181 | INFO | cdk_stacks.main | Pipeline creation/update of audit-password-policy commenced | (main.py:31) 
2019-11-12 14:53:13,247 | INFO | cdk_stacks.main | Pipeline creation/update of audit-cis-maintain commenced | (main.py:31) 
A newer version of the CDK CLI (>= 1.16.0) is necessary to interact with this app 
 
[Container] 2019/11/12 14:53:13 Command did not exit successfully cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null exit status 1 
[Container] 2019/11/12 14:53:13 Phase complete: BUILD State: FAILED 
[Container] 2019/11/12 14:53:13 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null. Reason: exit status 1 
[Container] 2019/11/12 14:53:13 Entering phase POST_BUILD 
[Container] 2019/11/12 14:53:13 Phase complete: POST_BUILD State: SUCCEEDED 
[Container] 2019/11/12 14:53:13 Phase context status code:  Message:

**Comment by bundyfx** [comment] 2019-11-12 15:08
@ErikMeinders Did you merge the PR in CodeCommit for the 2.1.2 update? It doesn't look like it as its still the old CDK + JSI version.

**Comment by ErikMeinders** [comment] 2019-11-12 15:30
@bundyfx Thanks for that, indeed didn't merge. Now it works - apart from the fact that I had added kms:Enable* to some policies to allow to Enable Key rotation (as per best practice). Would be nice if that would make it to the default permissions ... ;-)

**Comment by vchepkov** [comment] 2019-11-12 16:13
From what I can see tag 2.1.2 has been applied to some unrelated commit from 2 weeks ago.

**Comment by Suba-delo** [comment] 2019-11-12 17:30
> v2.1.2 is now on SAR which resolves updates CDK version to 1.16.2 along with updating some deprecated functionality. Please let me know how it goes.

@bundyfx Thank you :) The Pipeline works great with the new release 2.1.2!!

**Comment by at7925** [comment] 2019-11-12 18:42
2.1.2 Pipeline works well with cdk 1.16.2 changes but Release tag looks strage: https://github.com/awslabs/aws-deployment-framework/releases/tag/v2.1.2 (commit is not related to "cdk 1.16.2 changes")
@bundyfx , Was the ADF v2.1.2 release pushed to Serverless Application Repository from different repository?

**Comment by bundyfx** [comment] 2019-11-13 07:58
Ah yes, i have updated the release asset for v2.1.2, it was not valid.

**Comment by bundyfx** [comment] 2019-11-26 11:27
closing this one as this was related to a CDK version bump.

**Closed by bundyfx** 2019-11-26 11:27 UTC
