### ISSUE TITLE
[Bug]: aws-deployment-framework-base pipeline fails

### ISSUE THREAD

**Issue by Wildpipe** [awslabs/aws-deployment-framework#644] opened 2023-07-18 15:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Updating a deployment map and then running the aws-deployment-framework-base pipeline fails with 

```
[Container] 2023/07/18 14:22:14 Running command npm install aws-cdk@2.79 -g -y --quiet --no-progress

added 1 package in 2s

[Container] 2023/07/18 14:22:32 Running command aws s3 cp s3://$SHARED_MODULES_BUCKET/adf-build/ ./adf-build/ --recursive --quiet

[Container] 2023/07/18 14:22:50 Running command pip install -r adf-build/requirements.txt -r adf-build/helpers/requirements.txt -q -t ./adf-build
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      /tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/root/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-jayf5so3/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.1.1 -> 23.2
[notice] To update, run: pip install --upgrade pip

[Container] 2023/07/18 14:23:14 Command did not exit successfully pip install -r adf-build/requirements.txt -r adf-build/helpers/requirements.txt -q -t ./adf-build exit status 1
[Container] 2023/07/18 14:23:14 Phase complete: INSTALL State: FAILED
[Container] 2023/07/18 14:23:14 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: pip install -r adf-build/requirements.txt -r adf-build/helpers/requirements.txt -q -t ./adf-build. Reason: exit status 1
```

### Expected Behavior

It's possible to run the pipeline and have it update the codepipelines according to the deployment maps

### Current Behavior

The pipeline updating the other pipelines fails.

### Steps To Reproduce

Update a deployment map
Push it to version control system
Trigger a build of the aws-deployment-framework-base pipeline

### ADF Version

3.2

**Comment by Wildpipe** [comment] 2023-07-19 06:59
I believe this issue is related to a broken version PyYAML: https://github.com/yaml/pyyaml/issues/724

**Comment by sbkok** [comment] 2023-07-20 12:03
Unfortunately I cannot reproduce your issue with v3.2.0.
@Wildpipe can you please elaborate on the version you are running?

Specifically, I see your logs reference Python 3.11, which is a version that is not supported by CDK v1 that is used by ADF v3.2.0. Might you be running any patches that are merged in our main branch today?
It looks like you are running our CDK v2 patch at least. And what CodeBuild image is used specifically?

**Comment by Wildpipe** [comment] 2023-07-20 12:19
Yes, we are running the CDK v2 patch. 
For CodeBuild image we are running aws/codebuild/standard:7.0

I managed to "fix" the problem by implementing the following changes:

Comment out this line https://github.com/awslabs/aws-deployment-framework/blob/e348ed1a4144d26d0fd7ed6866c8a663f9111141/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/requirements.txt#L12

Append the following lines to https://github.com/awslabs/aws-deployment-framework/blob/e348ed1a4144d26d0fd7ed6866c8a663f9111141/src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml#L691

```
- pip install wheel
- pip install --no-build-isolation "Cython<3" "pyyaml==5.4.1"
```

Append the following lines to https://github.com/awslabs/aws-deployment-framework/blob/e348ed1a4144d26d0fd7ed6866c8a663f9111141/src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml#L667C35-L667C56

```
- pip install wheel
- pip install --no-build-isolation "Cython<3" "pyyaml==5.4.1"
```

Sorry, I wasn't aware we had diverged from main branch in terms of codebuild image.

**Comment by Wildpipe** [comment] 2023-07-20 12:24
Looking at the cdkv2 patch that seems to be what introduced the standard:7.0 change

**Comment by sbkok** [comment] 2023-07-20 12:38
Okay, phew. I am about to perform an upgrade of ADF v3.2.0 at another large installation.
I was worried this would impact v3.2.0 upgrades too, blocking our ability to upgrade.
I will get a PR in the main branch to fix this issue. Thanks for sharing that workaround.

**Closed** 2024-06-11 16:03 UTC
Labels: bug
