### ISSUE TITLE
3.0.1. accounts.yml processing failure

### ISSUE THREAD

**Issue by ErikMeinders** [awslabs/aws-deployment-framework#213] opened 2020-01-17 16:37 UTC
With an .yml file describing my existing accounts in place in the adf-accounts directory, a merge to master results in the error below.

[Container] 2020/01/17 16:20:46 Running command python adf-build/provisioner/main.py
151 | Traceback (most recent call last):
152 | File "adf-build/provisioner/main.py", line 100, in <module>
153 | main()
154 | File "adf-build/provisioner/main.py", line 23, in main
155 | accounts = read_config_files(ACCOUNTS_FOLDER)
156 | File "/codebuild/output/src067751763/src/adf-build/provisioner/src/configparser.py", line 21, in read_config_files
157 | for account in config.get('accounts', []):
158 | AttributeError: 'NoneType' object has no attribute 'get'
159

**Comment by bundyfx** [comment] 2020-01-18 09:18
Hi @ErikMeinders, 

Would you be able to post your .yml file contents in here with the sensitive data removed? This works as intended for me so I am guessing its a property in your config file. We *should* add schema validation to the .yml files in this directory also in the account config files also in the upcoming minor releases.

**Comment by ErikMeinders** [comment] 2020-01-18 14:29
A stale empty .yml file caused the issue. 

Now that's removed, it works a lot better. 

Remaining issue is for an account with a '_' in its full name. There is no alias defined and apparently in the absence of an alias, it tries to apply the full name as an alias. That failed as aliases don't support '_' chars.  

For another account, the name contains CAPITALS and so did the 'automagically' created alias. CAPS are not allowed in aliases.

After 'hardcoding' aliases for aliases-less accounts where _ and CAPS appeared in the account name (and thus in the implicit alias) with the illegal characters replaced, it works!

**Comment by bundyfx** [comment] 2020-02-17 10:27
Updating this one to be aligned with 3.0.5 release, docs are to be updated to mention the file must not be empty.. and error handing in yaml parsing should fail with invalid yaml error and mention this clearly in the codebuild output.

**Comment by sbkok** [comment] 2023-01-24 10:32
Thank you for your patience. I am happy to inform you that this issue has been [resolved in our latest release v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
I'm hereby closing this issue. Please open a new issue if you are experiencing any issues with the latest release.

**Closed by sbkok** 2023-01-24 10:32 UTC
Labels: enhancement
