### ISSUE TITLE
State Machine not found - First installation

### ISSUE THREAD

**Issue by lokeshkumarp** [awslabs/aws-deployment-framework#69] opened 2019-06-18 08:09 UTC
This issue happened only once and I apologize for not being detailed. I just wanted to log it here to see if anyone has seen this or if its even reproducible. 

Issue: Account bootstrapping failed with error StateMachine not found.

```
[ERROR] StateMachineDoesNotExist: An error occurred (StateMachineDoesNotExist) when calling the StartExecution operation: State Machine Does Not Exist: 'arn:aws:states:eu-west-1:652199396486:stateMachine:EnableCrossAccountAccess'
Traceback (most recent call last):
  File "/var/task/generic_account_config.py", line 40, in lambda_handler
    step_functions.execute_statemachine()
  File "/opt/python/stepfunctions.py", line 48, in execute_statemachine
    self._start_statemachine()
  File "/opt/python/stepfunctions.py", line 66, in _start_statemachine
    "error": self.error
  File "/var/runtime/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

This happened when i was bootstrapping the deployment account for the first time. In the step functions, once it determined if it was a create or update, instead of checking if its a deployment account it jumped to ExecutingDeploymentAccountStateMachine step and this is the place of failure. I was not able to find the actual root cause. I tried to move the deployment account to root and back with the same result. I did not try any other account type. Unfortunately i do not have the screenshot. 

Fix? I wouldn't call it a fix, but after i deleted ADF stack from my master account + paramter store and reinstalled it. It all seemed to work. Any idea what happened?

**Comment by bundyfx** [comment] 2019-06-18 10:03
Hi @lokeshkumarp 

Thanks for the logging the issue. What is happening here is a little misleading and its something we will fix up in the next release. What actually failed is the step before the *ExecutingDeploymentAccountStateMachine* step. It might of looked green in the console but it would of had a stack trace of the error within its JSON output. It was trying to pass this error along to the *ExecutingDeploymentAccountStateMachine* step as this is the step that ties in sending error notifications out to recipients via email or slack. The problem is of course is that if its the deployment account it clearly would not of existed yet..  

Was it possible that ADF had already been setup with this deployment/master account previously? if so there would of been a parameter in the master account named DeploymentAccountId - if this was already set when the bootstrapping occurred it would of caused this error. Thus removing the values from parameter store as you mentioned would of solved it. Im going to do some testing on this use-case and confirm my thoughts, will bundle what I find into the next minor release to ensure this error is contained and is well documented.

Again thanks for raising the issue!

**Comment by lokeshkumarp** [comment] 2019-06-18 17:31
Thanks for the details and the help. 

I can confirm the account never had ADF, i just created the account and installed ADF first thing.

**Comment by bundyfx** [comment] 2019-06-19 11:54
Thanks again, ill mark this as an enhancement and bug at the moment and ensure I spend some time digging into it over the next few days. This will go into v1.0.3 once we've worked out exactly what happened here but in general we will make the logging and error handling a bit more clear within the step function on the first run-through. I'll close this now and reference it in the v1.0.3 PR. If you have any issues related to this again please feel free to re-open this and include some extra details. 

Cheers!

**Closed by bundyfx** 2019-06-19 11:54 UTC
Labels: bug, enhancement
