### ISSUE TITLE
import keyword is not interpolated in leaf parameters file

### ISSUE THREAD

**Issue by vchepkov** [awslabs/aws-deployment-framework#147] opened 2019-08-29 20:45 UTC
import keyword is not interpolated and passed verbatim to pipeline if it is used in the leaf/final parameter file. i.e. if import keyword is used in AccountName_us-east-1.json, it is passed to pipeline, as-is, without interpolation. If it's used in global_us-east-1.json, for example, it is interpolated and merged into AccountName_us-east-1.json properly.

**Comment by vchepkov** [comment] 2020-02-28 14:54
Have you had a chance to look into this? That's really makes it difficult to deploy imported values  into different accounts. Thanks

**Comment by malikhijazi** [comment] 2020-12-21 18:23
+1

**Comment by mirceaadam** [comment] 2021-02-22 11:57
Hi,

+1

Using a potential workaround with a separate folder like "stage" with separate _buildspec.yml_  and only one _params/global.yml_ solves the issue but it's hard to work with and requires also updates in _deployment_map.yml_ .

Thank you

**Comment by sbkok** [comment] 2021-02-24 21:11
Thanks for reporting and raising how this impacted.
Apologies that we didn't fix this issue earlier.

I've been looking into it and found the root cause.
I will open a PR shortly to get it fixed in the next minor release.

**Closed** 2021-03-03 14:36 UTC
Labels: bug
