### ISSUE TITLE
ThrottlingException - on adf-deployment-framework

### ISSUE THREAD

**Issue by amimarkels** [awslabs/aws-deployment-framework#135] opened 2019-08-18 10:02 UTC
I assume that because we have more then 40 pipeline and because they run in different threads we get a "ThrottlingException - (reached max retries: 4): Rate exceeded" error **a lot** on the the adf-deployment-framework pipeline. 
trying to find a solution we came with boto allowing to increase the number of retries (https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html), but we are opened minded for a more elegant solution.

**Comment by amimarkels** [comment] 2019-08-18 15:00
After further investigation it is even a bigger issue. 
We have 50 pipelines. 
In each run of the adf-deployment-framework at least one stack is failing. 
The reason is that in `get_stack_status` the describe_stacks call fails due to throttling issue. Due to this it returns a value of 'None' and when trying to create it, it is failing on stack exist:

botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack [adf-pipeline-network-templates-xxx-us-east-1] already exists and cannot be created again with the changeSet [adf-pipeline-network-templates-xxx-us-east-1].

**Comment by bundyfx** [comment] 2019-08-18 16:01
Thanks @amimarkels 

Ok, I try replicate this myself and see if we can get a fix prioritized for this one. The stack [adf-pipeline-network-templates-xxx-us-east-1] most likely has a failed change set on it for a different reason, you can navigate to the CloudFormation failed change set in the console and see some related error information about it, ADF creates the same named change set each time it runs so it cannot create one if there is a failed change set already there.

I'll try replicate this now, we might need to change the config for retries as you suggested and also increase the frequency in which we check the stack status as part of the waiter.

**Comment by at7925** [comment] 2019-08-19 14:20
Lately experiencing the same *botocore.exceptions* :
```
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the PutParameter operation (reached max retries: 4): Rate exceeded 
```
and
```
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack [adf-pipeline-stackname] already exists and cannot be created again with the changeSet
```
we have 60+ pipelines and 30+ accounts

**Comment by bundyfx** [comment] 2019-08-19 14:39
> Lately experiencing the same _botocore.exceptions_ :
> 
> ```
> botocore.exceptions.ClientError: An error occurred (ThrottlingException) 
> when calling the PutParameter operation (reached max retries: 4): Rate exceeded 
> ```
> 
> and
> 
> ```
> botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateChangeSet operation: 
> Stack [adf-pipeline-stackname] already exists and cannot be created again with the changeSet
> ```
> 
> we have 60+ pipelines and 30+ accounts

Ah ok, so on Put Parameter call itself, interesting. And for this stack where the Change Set is failing to create, do you have a failed change set there with some more error information?

**Comment by at7925** [comment] 2019-08-19 15:12
>  And for this stack where the Change Set is failing to create, do you have a failed change set there with some more error information?

The stack is clean (no failed change set) and has successfully executed change set from few days back. Also re-running aws-deployment-framework-pipelines may complete with out errors or it may again show **cannot be created again with the changeSet** but for different stack

**Comment by bundyfx** [comment] 2019-08-20 08:10
Alright, So I think the first thing we should do here is adjust the config of the parameter store client to allow more than 4 (default) retries. This is outlined [here](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html). The next thing is we should introduce a random short delay between batches of threads. Say every 10 threads could be delayed by one or two seconds, this should be the first step and based on that we can adjust and move forward. Alternatively, you can increase the throughput of Parameter Store as outlined [here](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-throughput.html).

Another thing we should also change here is to not allow ADF to create CloudFormation stacks with None values that came back from parameter store. That is the issue that i believe is causing the problem with the change sets.

**Comment by bundyfx** [comment] 2019-08-21 09:04
v1.2.8 has been released on the SAR - Please give it a try and let me know if you have any throttled calls still. I tested this now with ~50 Pipelines and did not run into the issue. Essentially 1.2.8 introduces batching of threads (into chunks of 10) with a small delay inbetween. Also it adds in the retry logic to be 10 (up from default of 4). And another thing is ensuring the Waiter Delay for Cloudformation is a random amount of seconds, rather than having every thread check the stack status at the same time.

**Comment by at7925** [comment] 2019-08-21 12:56
Installed ADV v1.2.8 via SAR, pipeline "aws-deployment-framework-pipelines" looks stable. Botocore.exceptions stopped. I believe the issue is solved

**Comment by bundyfx** [comment] 2019-08-22 07:03
Great, closing this then.

**Closed by bundyfx** 2019-08-22 07:03 UTC
