### ISSUE TITLE
problem with adf-pipeline-provisioner-codebuild-role permissions

### ISSUE THREAD

**Issue by ehsanesteki** [awslabs/aws-deployment-framework#311] opened 2020-12-22 10:10 UTC
Hello Team,
I hade some problem with creation of new pipeline in ADF with the error:
![image](https://user-images.githubusercontent.com/29687622/102876746-f217a480-4445-11eb-8b1f-c877b1b709d6.png)
I fix this problem adding the AdministratorAccess Policies to role adf-pipeline-provisioner-codebuild-role:
![image](https://user-images.githubusercontent.com/29687622/102876893-2ab77e00-4446-11eb-8652-4fd3d22e0181.png)
Given AdministratorAccess is not good i think.
Can you help me to understand why this role doesn't work more?
Do you have another solution to give me please?
Thanks a lot.

**Comment by at7925** [comment] 2020-12-22 16:10
I bet you have multiple regions deployments! 
The same same error happens for a fist time on 18-dec-2020 for me as well, the funny thing about the error:it references not the region where pipelines are placed. So the failing action should not even happened. Likely some new elements are introduced in AWS. 
Also quick research in cloud-trail shows shows another new error happening at the same time:
```
User: arn:aws:sts::111111111111111:assumed-role/adf-pipeline-provisioner-codebuild-role/AWSCodeBuild-5598901a-851f-4048-9e11-aaaaaaaabbbbbcc is not authorized to perform: iam:TagRole on resource: arn:aws:iam::111111111111111:role/adf-pipeline-org-managedo-codepipelineeventspipeli-ERBERERB
```
To solve these errors a small change in adf-bootstrap/deployment/global.yml is required in **adf-pipeline-provisioner-codebuild-policy**
you can still apply a quick workaround into adf-bootstrap/deployment/global-iam.yml

**Comment by steynovich** [comment] 2020-12-23 12:45
I'm facing the same issue, at multiple ADF deployments. I've noticed that the permission denied error is complaining about not having permissions on the pipeline in `eu-central-1`, while the pipeline sits in `eu-west-1`. Also the API call was made to `eu-west-1`. Still the error message is complaning about `eu-central-1`. I'm also able to reproduce this error using the awscli. So I suspect something is wrong in CodePipeline/IAM and not in ADF.

**Comment by at7925** [comment] 2020-12-23 13:56
steynovich said>  So I suspect something is wrong in CodePipeline/IAM and not in ADF.
I bet the problem in AWS CloudFormation, 
CloudFoamrtion performs some shadow actions in non-primary region as result  **adf-pipeline-provisioner-codebuild-role** with strict permissions to create pipeline only in primary primary region fails
It's better to solve the problem in AWS, until then my workaround fix allows ADF to work
Sure, we can simply make change in adf-bootstrap/deployment/global.yml 
```
-              - !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelinePrefix}*
+              - !Sub arn:aws:codepipeline:*:${AWS::AccountId}:${PipelinePrefix}*
```
to fix issue in next ADF release but it better be fixed in AWS CloudFormation instead

**Comment by steynovich** [comment] 2020-12-23 13:59
> steynovich said> So I suspect something is wrong in CodePipeline/IAM and not in ADF.
> I bet the problem in AWS CloudFormation,
> CloudFoamrtion performs some shadow actions in non-primary region as result **adf-pipeline-provisioner-codebuild-role** with strict permissions to create pipeline only in primary primary region fails
> It's better to solve the problem in AWS, until then my workaround fix allows ADF to work
> Sure, we can simply make change in adf-bootstrap/deployment/global.yml
> 
> ```
> -              - !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelinePrefix}*
> +              - !Sub arn:aws:codepipeline:*:${AWS::AccountId}:${PipelinePrefix}*
> ```
> 
> to fix issue in next ADF release but it better be fixed in AWS CloudFormation instead

No, I also see the same issue when running awscli: `aws codepipeline update-pipeline --cli-input-json file://pipeline.json`

**Comment by at7925** [comment] 2020-12-23 14:10
> > steynovich said> So I suspect something is wrong in CodePipeline/IAM and not in ADF.
> > I bet the problem in AWS CloudFormation,
> > CloudFoamrtion performs some shadow actions in non-primary region as result **adf-pipeline-provisioner-codebuild-role** with strict permissions to create pipeline only in primary primary region fails
> > It's better to solve the problem in AWS, until then my workaround fix allows ADF to work
> > Sure, we can simply make change in adf-bootstrap/deployment/global.yml
> > ```
> > -              - !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelinePrefix}*
> > +              - !Sub arn:aws:codepipeline:*:${AWS::AccountId}:${PipelinePrefix}*
> > ```
> > 
> > 
> > to fix issue in next ADF release but it better be fixed in AWS CloudFormation instead
> 
> No, I also see the same issue when running awscli: `aws codepipeline update-pipeline --cli-input-json file://pipeline.json`
Ok, I see.. in this case you are right problem in AWS:CodePipeline API. At the same time ADF does not make 'aws codepipeline' calls but simply execution CloudFormation deploy.
Any way, today **adf-pipeline-provisioner-codebuild-role** is missing permissions to make codepipeline:* actions in non-primary regions

**Comment by sbkok** [comment] 2020-12-30 17:57
The issue has been identified and the team is working on a fix. We will post an update to this thread once the fix is rolled out. Thanks for bringing this to our attention.

**Comment by benbridts** [comment] 2020-12-30 18:08
@sbkok out of curiosity: is there a reason that development of new versions isn't done in this repository? I know it can be annoying to work in the open, but early customer feedback can also be very valuable.

**Comment by sbkok** [comment] 2020-12-30 18:38
As @at7925 and @steynovich figured out, this seems to be a service issue. I've reported the problem to the team and they are working on a fix which is not part of this code base. That is why :)

Quickest way to work around the problem, is to add the regions that you need in the adf-bootstrap/deployment/global.yml file. Like @steynovich pointed out, but then using the specific regions that you need to target.
Changing [the resource for the codepieline actions](https://github.com/awslabs/aws-deployment-framework/blob/31f4719f83e80bd165b1567fed27de8eff090460/src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml#L438) from:
```
- !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:webhook:adf-webhook-*
- !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelinePrefix}*
```

For example,  in case your other regions (as the AWS::Region points to the deployment region) would be `eu-central-1` and `us-east-1`, to:
```
- !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:webhook:adf-webhook-*
- !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelinePrefix}*
- !Sub arn:aws:codepipeline:eu-central-1:${AWS::AccountId}:${PipelinePrefix}*
- !Sub arn:aws:codepipeline:us-east-1:${AWS::AccountId}:${PipelinePrefix}*
- # etc.
```

**Comment by sbkok** [comment] 2021-02-16 11:33
Apologies for the late reply. I just read that the fix has been deployed to all regions 19 days ago.
So this problem should be resolved. Please let me know if it is or whether you are still experiencing an issue.
Please close the ticket if this issue is fixed.

Best regards, Simon

**Comment by sbkok** [comment] 2021-02-25 13:35
I'm closing this issue as it has been resolved by the AWS service team and no issues have been reported after.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases). Thank you!

**Closed by sbkok** 2021-02-25 13:35 UTC
