### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (OptInRequired) when calling the DescribeRegions operation: You are not subscribed to this service. Please go to http://aws.amazon.com to subscribe.

### ISSUE THREAD

**Issue by infraavanxo** [awslabs/aws-deployment-framework#283] opened 2020-07-24 22:20 UTC
Hello

I am using ADF version 3.0.5 and when I try to create new accounts I get the following error into CodeBuild:

botocore.exceptions.ClientError: An error occurred (OptInRequired) when calling the DescribeRegions operation: You are not subscribed to this service. Please go to http://aws.amazon.com to subscribe.

Regards,

VIctor BArrios

**Comment by sbkok** [comment] 2020-07-28 08:12
Hi Victor,

Could you share which region you are setting up?
Plus did you configure this as the default region or one of the regions?

It looks like you are trying to deploy ADF into one of the Opt-in regions.
We need to verify if all the services that ADF relies on are available in that region.

Many thanks, Simon

**Comment by StewartW** [comment] 2020-07-29 11:24
> Hi Victor,
> 
> Could you share which region you are setting up?
> Plus did you configure this as the default region or one of the regions?
> 
> It looks like you are trying to deploy ADF into one of the Opt-in regions.
> We need to verify if all the services that ADF relies on are available in that region.
> 
> Many thanks, Simon

Hey Simon, 
I think this is actually a timing issue. 
I've seen it once or twice when creating new accounts (Usually when trying to delete the default VPC), re-running usually solves this as a work around. 

I think it would be solved through [This Project](https://github.com/awslabs/aws-deployment-framework/projects/2)

**Comment by deltagarrett** [comment] 2020-07-29 11:51
Hi Stewart, as highlighted in https://github.com/awslabs/aws-deployment-framework/pull/238, it is related to the fact  that some AWS services take some time (minutes) before being activated in the newly created accounts. As you mentioned, Step Functions project or any other retry logic will fix this. If you agree I will close the issue.

**Comment by sbkok** [comment] 2021-03-02 17:37
I'm closing this issue as it has been inactive for a long period. This probably means that it is not reproducible or it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases). Thank you!

**Closed by sbkok** 2021-03-02 17:37 UTC
