### ISSUE TITLE
Pipeline fails due to incompatibility issue

### ISSUE THREAD

**Issue by subhadharun** [awslabs/aws-deployment-framework#175] opened 2019-10-31 08:24 UTC
When there is a pipeline trigger, i get an error stating "aws-cdk incompatible" .
 
[Container] : Running command pip install -r adf-build/requirements.txt -q -t ./adf-build 
**ERROR: aws-cdk-aws-cloudwatch 1.15.0 has requirement aws-cdk.aws-iam>=1.15.0,~=1.15, but you'll have aws-cdk-aws-iam 1.13.1 which is incompatible.** 

I had the version 1.12.1. I tried updating it to version 2.1.0(after the new release), but it still gives this error. Is that an application issue or is there a fix for this to be tried ?

**Comment by bundyfx** [comment] 2019-10-31 08:46
Hi @subhadharun 

The pipeline should not actually fail from this "error". If that is the case, please let us know! You mentioned you upgraded to 2.1.0 already? I am also on 2.1.0 and I don't see this error message output.. can you post your Info output from the codebuild container? including version etc.

**Comment by subhadharun** [comment] 2019-10-31 08:53
![image](https://user-images.githubusercontent.com/46345205/67932138-acee3e80-fbc3-11e9-83af-d2d688f2d3f4.png)
![image](https://user-images.githubusercontent.com/46345205/67932285-dd35dd00-fbc3-11e9-9d5b-b22ac75550a7.png)

The above explains the current version at the master account and then the Pipeline failing from the deployment account. I dont think i have to make any changes the deployment account related to the Code build ? or is there something missing ?

**Comment by subhadharun** [comment] 2019-10-31 09:43
The top image was from the Master account, and i now managed to MERGE the code. Now the Pipeline form the Master account failed , with the following error.
![image](https://user-images.githubusercontent.com/46345205/67935976-36553f00-fbcb-11e9-95eb-a32bc7ee56ff.png)

**Comment by subhadharun** [comment] 2019-11-01 09:41
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/46345205/68015879-7ed82f80-fc93-11e9-9997-ea99fcb8d6b3.png">

Now, when i re-released the pipeline again i see the above error. The error indicates, target path failed to return to a child OU. The specified path was Custom/xxxxxxxxxx , where the test works when i specify the Parent OU,but for the child OU. I can still proceed with Custom OU, whereas it will be okay if there is only one child OU. Any suggestions on how to fix this?

**Comment by bundyfx** [comment] 2019-11-01 11:04
Do you have an OU at /Custom/Source? - ADF cannot target OUs that dont exist. Nor can it target a collection of OUs under a path.

For example, if you have two OUs under /Custom, one called test and one called dev. You cannot target them both by saying **'/Custom'**, you need to explicitly use their path in the targets. Regardless, the error suggests you don't have an OU with the name you are targeting.

**Comment by subhadharun** [comment] 2019-11-01 11:27
Thank you @bundyfx 
This time i tried the target path with - "/custom/xxxxxxxx" and that works. Later i would also like to test the path - "/Custom/*". I think we are good with this issue now. 

Also, i see new releases of the ADF versions once in a while. I used **2.0.3** version 10 days ago, and today it is **2.1.1**.How often do you think,the ADF version needs an update going forward? As you have locked the version of cdk @1.13.1,will that not affect the pipeline anymore?

**Comment by bundyfx** [comment] 2019-11-01 11:35
Great! As I mentioned above, currently we don't support the concept of wildcards in paths such as "/Custom/*" so this will **not** work today. ADF will continue to evolve based on feedback and what users would like to see, at the moment we want to focus on stability, error handling and security. CDK is locked to 1.13.1 currently however we will upgrade this every few releases or so, currently CDK is exclusively being used as part of the generate pipelines pipeline so we don't need to constantly keep it on the latest version as it is working as intended as of 1.13.1. Ill close this one for now!

Thanks again!

**Closed by bundyfx** 2019-11-01 11:35 UTC
