### ISSUE TITLE
ADF fails to bootstrap new account declared in adf-accounts

### ISSUE THREAD

**Issue by hynynen** [awslabs/aws-deployment-framework#243] opened 2020-02-14 14:52 UTC
What I did: 

1. Define new account in bootstrapping repo under adf-accounts
2. Bootstrapping pipeline creates the account and moves it to correct ou
3. Step functions is triggered
4. Step 'CreateOrUpdateBaseStack' fails.

The error is:
`
"error": {
    "Error": "ClientError",
    "Cause": "{\"errorMessage\": \"An error occurred (SubscriptionRequiredException) when calling the GetParameter operation: The AWS Access Key Id needs a subscription for the service\", \"errorType\": \"ClientError\", \"stackTrace\": [\"  File \\\"/var/task/account_bootstrap.py\\\", line 109, in lambda_handler\\n    configure_generic_account(sts, event, region, role)\\n\", \"  File \\\"/var/task/account_bootstrap.py\\\", line 58, in configure_generic_account\\n    parameter_store_target_account.put_parameter('kms_arn', kms_arn)\\n\", \"  File \\\"/opt/python/parameter_store.py\\\", line 31, in put_parameter\\n    current_value = self.fetch_parameter(name)\\n\", \"  File \\\"/opt/python/parameter_store.py\\\", line 78, in fetch_parameter\\n    WithDecryption=with_decryption\\n\", \"  File \\\"/var/runtime/botocore/client.py\\\", line 272, in _api_call\\n    return self._make_api_call(operation_name, kwargs)\\n\", \"  File \\\"/var/runtime/botocore/client.py\\\", line 576, in _make_api_call\\n    raise error_class(parsed_response, operation_name)\\n\"]}"
  }
`
It got bootstrapped correctly after moving it to root and back to OU again.

**Comment by bundyfx** [comment] 2020-02-17 10:17
Thanks @hynynen - This appears to be some issue around timing when creating new accounts.. the new account does not appear to be fully initialized by the time some of the API calls are made and thus returns this vague unrelated error. We will look into this and try to tighten up the whole account creation process to ensure it is smooth as part of the next release.

**Comment by mdaehnert** [comment] 2020-06-02 11:51
Temporarily workaround was released with version 3.0.6. ([wait 30 seconds --> 90 seconds](https://github.com/awslabs/aws-deployment-framework/pull/261/files#diff-f47c805f0dd7e769092ac78c5b434ed4)).

Hint: It's a first workaround, but isn't working all the time. I therefore recommend people who are running into this issue to change this value up to 300 (5 min).

**Comment by rosmild** [comment] 2021-06-17 08:12
Hi All,
I've increased the value from 90 to 300 but I'm still running into the issue.

**Comment by deltagarrett** [comment] 2021-06-17 08:30
Hi @rosmild , which ADF version are you running? I'm currently running latest available (3.1.2) and I'm not running in this issue and I'm creating a lot of new accounts in the last days. Wondering which version you are running because we added some fix around this topic on latest releases.

**Comment by rosmild** [comment] 2021-06-17 09:29
Hi @deltagarrett,
thanks for your prompt feedback, we are using 3.1.2. 
In the meantime I've investigated the issue further and I wonder if it depends on the account must be created on eu-south-1 region. 
I'm saying this because this region is not enabled by default on new accounts and we must enable it manually.

**Comment by deltagarrett** [comment] 2021-06-17 11:23
Accounts are globally created and not in a region so we can't create account in a region, but just call Organizations API to create an account: https://github.com/awslabs/aws-deployment-framework/blob/da7ac5fdf03faccc5146340895f92a0f91770a3e/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/organizations.py#L330 . 

However I can understand you have eu-south-1 as bootstrapped region in ADF. Of course you want to have it bootstrapped on newly created accounts but:
- at current point in time there is no public API to enable opt-in regions (Milan, Cape Town, ... and all 2019+ regions https://docs.aws.amazon.com/general/latest/gr/rande-manage.html )
- enabling a region several minutes (5-10 or more mins)

At the moment the best approach I've found can be:
1. Create the account in the root of the org: `organizational_unit_path: /`
2. Manually enable required opt-in regions
3. Move the account to the proper ou (`organizational_unit_path: /xyz`)
4. Let ADF do the rest of the job (bootstrapping, update pipelines, ...)

Of course, when AWS will release a public API to enable regions we should update the account management part including this capability. 

More than happy to listen other workarounds from the community. ; )

**Comment by rosmild** [comment] 2021-06-18 06:46
Hi @deltagarrett,
thanks again for your support. I'm using the suggested workaround and I confirm it's woking fine.

**Comment by sbkok** [comment] 2021-11-08 17:13
I'm closing this issue as it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases).

Thank you!

**Closed by sbkok** 2021-11-08 17:13 UTC
Labels: bug
